name: pypsa-nrw
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.10
- pip

# Add additional packages only to pypsa-de specific section
# All other packages should be identical to pypsa-eur (in best case the same, otherwise
# maybe different pins)

# pypsa-de specific
- pycountry
- pyam>=2.0
- ruamel.yaml
- jpype1

# Inhouse packages
- pypsa>=0.32.1
- atlite>=0.3
- linopy>=0.4.4
- powerplantmatching>=0.5.15,<0.7 # restrict ppm until fix of https://github.com/PyPSA/powerplantmatching/issues/229

# Dependencies of the workflow itself
- dask
- xlrd
- openpyxl
- seaborn
- snakemake-minimal>=9
- memory_profiler
- yaml
- pytables
- lxml
- numpy
- pandas>=2.1
- geopandas>=1
- xarray>=2024.03.0
- rioxarray
- netcdf4
- libgdal-netcdf
- networkx
- scipy
- glpk
- shapely>=2.0
- matplotlib
- proj
- fiona
- country_converter
- geopy
- tqdm
- pytz
- tabula-py
- pyxlsb
- graphviz
- geojson

# GIS dependencies:
- cartopy
- descartes
- rasterio

# Development dependencies
- jupyter
- ipython
- pre-commit
- ruff
- pylint

- pip:
  - gurobipy
  - highspy
  - pyscipopt # See https://github.com/scipopt/PySCIPOpt/issues/944
  - tsam>=2.3.1
  - entsoe-py
  - snakemake-storage-plugin-http>=0.3
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-cluster-generic
